### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by PushkarOP** [OguzhanUmutlu/webchess#1]
Not able to move da queen....

**Comment by PushkarOP** [comment]
side ways*

**Comment by PushkarOP** [comment]
![image](https://github.com/OguzhanUmutlu/webchess/assets/84075300/2ddcca14-e32b-47f5-b0e6-ab17e7b0072a)
need pawn promotion feature....

**Comment by OguzhanUmutlu** [comment]
> Not able to move da queen....

I fixed the queens movement with this commit: aaac03fb41207b66bf5345d4ae432b3df593ea78

**Comment by OguzhanUmutlu** [comment]
> need pawn promotion feature....

There actually was a pawn promotion feature but another feature I added had broken it... I've fixed it though in the following commit: 0d058e2066cb92ef2185fb9156adc1daf04bb50f

**Comment by OguzhanUmutlu** [comment]
Thanks for the bug reports.
